### ISSUE TITLE
Request: add support for tokenKey

### ISSUE THREAD

**Issue by stevelacy** [azuqua/jwt-redis-session#19]
Currently the JWT is added to the `req.[requestKey].jwt`.
I am requesting adding another option for setting the param `jwt` such as:
```js
JWTSession({
  client: redis,
  secret: 'kat',
  requestKey: 'session',
  tokenKey: 'token'
})

// => req.session.token = JWT
```
I can send a PR to add the option along with tests.

**Comment by ricardosw** [comment]
And if possible, add an option that keep the `requestArg` the same that was written (do not transform to 'x-some-thing' what was 'someThing'). What you think, @stevelacy?

**Comment by aembke** [comment]
That sounds like a good idea. I can shoot to get that added in the next week or so, or if you need it sooner feel free to submit a PR.

**Comment by aembke** [comment]
Was bored in a meeting, here's a PR that should take care of these. 

https://github.com/azuqua/jwt-redis-session/pull/20

Feel free to give it a try and I'll push it to npm next week.

**Comment by aembke** [comment]
Now being tracked here: https://github.com/azuqua/jwt-redis-session/pull/21

**Comment by stevelacy** [comment]
I tried it out, seems to be working well, thanks
