### ISSUE TITLE
Destroying other user sessions

### ISSUE THREAD

**Issue by stevelacy** [azuqua/jwt-redis-session#24]
One of the benefits of having a redis backed session store is the ability to delete all sessions for a particular user.
It seems that the `destroy` function only deletes the current `req.session` by it's corresponding ID in redis. Could deleting all sessions by a particular user's ID be added?

**Comment by akaNightmare** [comment]
@stevelacy https://github.com/azuqua/jwt-redis-session/blob/master/lib/jwtRedisSession.js#L41

**Comment by stevelacy** [comment]
Not quite - that just gets the current session from the current JWT - not all the concurrent sessions associated with a user.

**Comment by akaNightmare** [comment]
You can generate almost same token for another user and delete it from redis directly

**Comment by stevelacy** [comment]
Yeah, definitely not what I want to do, thats basically creating half of this project in my app.

BTW I forked and added support for managing user based sessions:
https://github.com/stevelacy/jwt-redis-session/commit/45acf240a2ea76f5c6ec15c76a930034a3de5bde

**Comment by stevelacy** [comment]
```js
export const purge = async (user) => {
  client.scan(0, 'MATCH', `sess:${user.id}:*`, 'COUNT', 10, (err, res) => {
    if (err) return
    if (res[1] && res[1].length > 0) {
      res[1].forEach((key) => client.del(key))
    }
  })
}
```
