### ISSUE TITLE
Error if "x-access-token" header is not set

### ISSUE THREAD

**Issue by marcstark** [azuqua/jwt-redis-session#9]
If the header field - for example with the "x-access-token" label - is not set, the package throws an error:

```
Cannot read property 'accessToken' of undefined
```

That means, routes without the header label are not possible. Also, it is a possible vulnerability for attacks.

**Comment by nickclaw** [comment]
Seems to only be an issue if your not reading the request body. Does it work as expected if you add [body-parser](https://www.npmjs.com/package/body-parser) somewhere above this middleware?

Not sure how that makes a vulnerability. Could you give an example?

**Comment by marcstark** [comment]
Yes, by using the body-parser, it works. But since I don't use it (, yet), and in general people might not use a body parser (with a session server for example), maybe something like

```
var token = req.get(requestHeader) ||
			req.query && req.query[options.requestArg] ||
			req.body && req.body[options.requestArg] ||
			false;
```

would be a saver solution. Don't you think?

**Comment by nickclaw** [comment]
Definitely, while we can guarantee that `req.get()`, and `req.query` will exist, `req.body` might not. A fix will be published soon, until then just keep body-parser.
